# .streamlit/secrets.toml

[postgres]
db_url = "postgresql://neondb_owner:npg_Rd1vkhV7oCIg@ep-curly-mountain-ae52d80a-pooler.c-2.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require"



# .streamlit/secrets.toml

[client_codes]

"7-ELEVEN MEXICO SA DE CV" = "2794"
"ANA COMPAÑÍA DE SEGUROS" = "8439"
"ADMINISTRACIÓN  VENTURA SA DE  CV " = "9156"
"AFORE XXI BANORTE S.A DE C.V" = "4021"
"GRUPO DRAGON" = "4679"
"AIG" = "7005"
"ALD AUTOMOTIVE, S.A. DE C.V" = "7832"
"ALLIANZ MEXICO SA COMPAÑIA DE SEGUROS" = "1246"
"ARIMECHU SC" = "4403"
"ARIZA DE MEXICO SA DECV" = "2348"
"ACTINVER" = "4397"
"ASEGURADORA B" = "1587"
"AUTOS Y SALVAMENTOS, S.A. DE C.V." = "6967"
"ESTAFETA" = "3226"
"AXA SEGUROS S.A. DE C.V." = "3161"
"BALA EXPRESS S.A DE C.V" = "9123"
"BAFAMSA" = "5598"
"BANCO AZTECA, S.A. INSTITUCIÓN DE BANCA MULTIPLE" = "9873"
"BANCO MERCANTIL DEL NORTE, S. A. (BANORTE)" = "1776"
"BBVA LEASING MEXICO SA DE CV" = "8173"
"BDF CORPORATIVO SA DE CV" = "8454"
"BERRYMEX S DE RL DE CV" = "8989"
"BINARIO DEL NORTE" = "8968"
"BMW FINANCIAL SERVICES DE MEXICO SA DE CV SOFOM  ENR" = "9666"
"BMW LEASING DE MEXICO SA DE CV" = "6224"
"CA FINANCIAL SERVICES SAPI DE CV" = "3582"
"CA SOLUCIONES FINANCIERAS SA DE CV" = "6231"
"CALIDAD EN RECURSOS Y SERVICIO SA DE CV  (CARSSA)" = "3831"
"CASANOVA" = "5954"
"CHUBB" = "1392"
"DISH" = "6631"
"LALA" = "6085"
"PEPSICO" = "9642"
"CONAUTO" = "9402"
"CONTROLADORA VENTURA  SA DE CV" = "6600"
"CORPORATIVO GAVIOTAS" = "3043"
"CUENCA DEL PLATA HOLDING SA DE CV" = "3589"
"ELEMENT" = "1127"
"DHL" = "8918"
"EDGEWELL PERSONAL CARE MEXICO  SA DE CV" = "2538"
"EL AGUILA COMPAÑIA DE SEGUROS" = "7035"
"ENDOFLET" = "1406"
"ENERGIZER MEXICO, S. DE R.L. DE C.V." = "5229"
"ENERGIZER SERVICES MEXICO S DE RL DE CV" = "9707"
"FEMSA" = "5868"
"FINANCIERA AUTOPCION" = "2319"
"FINVIVIR" = "2893"
"FRAMAR DEL GOLFO, S DE RL DE MI" = "9922"
"FRANCISCO JAVIER RODRIGUEZ GUERRERO" = "5215"
"GENERAL DE SEGUROS" = "1701"
"GLAFASA SA DE CV" = "7319"
"GLOBAL MOTORS LEASING S.A DE C.V." = "4924"
"GM FINANCIAL DE MEXICO PERSONAS FISICAS" = "5484"
"GM FINANCIAL DE MÉXICO, S.A. DE C.V. SOFOM ER" = "8704"
"GRUPO EMPRESARIAL GONDEL MEXICO SA DE CV" = "6103"
"GRUPO SALINAS" = "7786"
"HDI SEGUROS S.A. DE C.V." = "1754"
"HDI SEGUROS S.H. DE C.V." = "3989"
"HDM SEGUROS S.A. DE C.V." = "3650"
"IMPULSORA SAHUAYO, S.A. DE C.V." = "1002"
"IENOVA" = "7582"
"JHONSON & JHONSON SA DE CV" = "3474"
"LA LATINOAMERICANA SEGUROS, S.A" = "1546"
"LEASEPLAN MEXICO SA DE CV" = "4925"
"LUMO FINANCIERA DEL CENTRO, S.A. DE C.V." = "6334"
"MEXICANA DE LUBRICANTES SA DE CV" = "8648"
"MONARCA BERRIES" = "7002"
"NAZRE HASSAM ASSAD JACQUES" = "3451"
"NESTLÉ SERVICIOS CORPORATIVOS S.A. DE C.V." = "3285"
"OFICINA COORDINADORA DE RIESGOS ASEGURADOS, S.C." = "5337"
"FMA" = "1362"
"PEPSICO NV" = "6756"
"PERSONNA INTERNATIONAL DE MEXICO SA DE CV" = "3654"
"POCHTECA MATERIAS PRIMAS" = "7230"
"PRESTAMOS AUTO EFECTIVO" = "9447"
"PRIMERO SEGUROS SA DE CV" = "3758"
"PRONTO REPARTOS RAPIDOS SA DE CV" = "4512"
"PROPIMEX" = "5160"
"QUALITAS COMPAÑÍA DE SEGUROS S.A. DE C.V. " = "1194"
"REFERIDOS EOL" = "6296"
"REPARTOS RAPIDOS DE COLIMA, S. A. DE C. V." = "7594"
"REPARTOS RAPIDOS DE MICHOACAN, S. A. DE C.V." = "4116"
"REPARTOS RAPIDOS DE SINALOA SA DE CV" = "3957"
"REPARTOS RAPIDOS DEL BAJIO" = "9160"
"REPARTOS RAPIDOS DEL NAYAR, S. A. DE C. V." = "5088"
"REPARTOS RAPIDOS JALISCO, S.A. DE C. V." = "5825"
"REPARTOS RAPIDOS SA DE CV" = "2267"
"ROGUER DEL SUR DE TAMAULIPAS S DE RL MI" = "6911"
"RYDER CAPITAL, S. DE R.L DE C.V" = "8838"
"SEGUROS AFIRME, S.A. DE C.V." = "5364"
"SEGUROS ATLAS, S. A." = "3676"
"SEGUROS AZTECA" = "1265"
"BANORTE" = "4898"
"SEGUROS EL POTOSI S.A." = "5934"
"SEGUROS MULTIVA S.A." = "3734"
"SEVEN ELEVEN" = "7742"
"SICREA" = "4402"
"SINIESTROS DIVERSOS SEGUROS BANORTE GENERALI" = "6077"
"SOCIEDAD AUTOMOTRIZ LEGA S.A. DE C.V." = "2452"
"SOLUFI " = "2089"
"SUBASTAS VENTURA S.A. DE C.V." = "3675"
"SURTIDORA DE TRACTOCAMIONES Y REFACCIONES SA DE CV" = "9748"
"SV CHATARRA" = "5843"
"AVIGRUPO" = "8684"
"TRANSPORTES UNIDOS CASTAÑEDA S A P I DE CV" = "1872"
"VALBO" = "8842"
"TURISMO GARGO SA DE CV" = "1392"
"UNIFIN FINANCIERA" = "3365"
"VALUE" = "9580"
"VENTAS PARTICULARES" = "2037"
"VENTURA EMPEÑOS" = "5977"
"VIAL ASSIST" = "6326"
"ZURICH ASEGURADORA MEXICANA" = "2772"
"GRUPO PIRAMIDE" = "4660"
"FINANCIERA POR EL IMPULSO ECONOMICO S.A.DEC.V., SOFOM,E.N.R." = "1515"
"BTLC LATAM" = "4078"


# todos los clientes 
